# Generated by Django 4.1.7 on 2023-09-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255, verbose_name='Product Name')),
                ('Description', models.TextField(verbose_name='Product Description')),
                ('Composition', models.TextField(verbose_name='Composition')),
                ('ProductImage', models.ImageField(null=True, upload_to='product')),
                ('ProductFile', models.FileField(null=True, upload_to='Files')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SubCategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('SubCategoryName', models.CharField(max_length=255, verbose_name='Sub Category Name')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customadminpanel.category', verbose_name='Category Name')),
            ],
        ),
    ]
