# Generated by Django 4.1.7 on 2023-09-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0002_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customadminpanel.category', verbose_name='Category Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customadminpanel.subcategory', verbose_name='Sub Category Name'),
            preserve_default=False,
        ),
    ]
