# Generated by Django 4.1.7 on 2023-09-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0003_product_category_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductFile',
            field=models.FileField(null=True, upload_to='media/Files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
    ]
