# Generated by Django 4.1.7 on 2023-09-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0004_alter_product_productfile_alter_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('ProductDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Field1', models.CharField(blank=True, max_length=255, verbose_name='Field1')),
                ('Field2', models.CharField(blank=True, max_length=255, verbose_name='Field2')),
                ('Field3', models.CharField(blank=True, max_length=255, verbose_name='Field3')),
                ('Field4', models.CharField(blank=True, max_length=255, verbose_name='Field4')),
                ('Field5', models.CharField(blank=True, max_length=255, verbose_name='Field5')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customadminpanel.product', verbose_name='Product Name')),
            ],
        ),
    ]
