# Generated by Django 4.1.7 on 2023-09-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0005_productdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
