# Generated by Django 4.1.7 on 2023-09-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.category', verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.subcategory', verbose_name='Sub Category Name'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.category', verbose_name='Category Name'),
        ),
        migrations.CreateModel(
            name='SubProductDetail',
            fields=[
                ('SubProductDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Field1', models.CharField(blank=True, max_length=255, verbose_name='Field1')),
                ('Field2', models.CharField(blank=True, max_length=255, verbose_name='Field2')),
                ('Field3', models.CharField(blank=True, max_length=255, verbose_name='Field3')),
                ('Field4', models.CharField(blank=True, max_length=255, verbose_name='Field4')),
                ('Field5', models.CharField(blank=True, max_length=255, verbose_name='Field5')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.product', verbose_name='Product Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('SubProductID', models.AutoField(primary_key=True, serialize=False)),
                ('SubProductName', models.CharField(max_length=255, verbose_name='Sub Product Name')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Composition', models.TextField(verbose_name='Composition')),
                ('ProductImage', models.ImageField(null=True, upload_to='media/product')),
                ('ProductFile', models.FileField(null=True, upload_to='media/Files')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.category', verbose_name='Category Name')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.product', verbose_name='Main Product Name')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.subcategory', verbose_name='Sub Category Name')),
            ],
        ),
    ]
