# Generated by Django 4.1.7 on 2023-09-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0007_alter_product_category_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproductdetail',
            name='Product',
        ),
        migrations.AddField(
            model_name='subproductdetail',
            name='SubProduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.subproduct', verbose_name='Sub Product Name'),
            preserve_default=False,
        ),
    ]
