# Generated by Django 4.1.7 on 2023-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0008_remove_subproductdetail_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=255, verbose_name='Project Name')),
                ('ProjectImage', models.ImageField(null=True, upload_to='media/product')),
                ('StartDate', models.DateField(verbose_name='Project Start Date')),
                ('EndDate', models.DateField(verbose_name='Project End Date')),
                ('Description', models.TextField()),
            ],
        ),
    ]
