# Generated by Django 4.1.7 on 2023-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('PartnerID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
                ('Link', models.URLField(max_length=5000)),
            ],
        ),
    ]
