# Generated by Django 4.1.7 on 2023-09-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0010_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
                ('Link', models.URLField(max_length=5000)),
            ],
        ),
    ]
