# Generated by Django 4.1.7 on 2023-09-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0011_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedMachineryImages',
            fields=[
                ('UMID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
            ],
        ),
        migrations.CreateModel(
            name='UsedMachine',
            fields=[
                ('UsedMachineID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Machine Name')),
                ('Description', models.TextField()),
                ('Ref', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('Year', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('Brand', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('Status', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('DeliveryTime', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('NumberOfStation', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('Output', models.CharField(blank=True, max_length=255, verbose_name='Reference No')),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadminpanel.usedmachineryimages', verbose_name='Machine Images')),
            ],
        ),
    ]
