# Generated by Django 4.1.7 on 2023-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0013_usedmachineryimages_name_alter_usedmachine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmachine',
            name='Image2',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
        migrations.AddField(
            model_name='usedmachine',
            name='Image3',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
        migrations.AddField(
            model_name='usedmachine',
            name='Image4',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
        migrations.AddField(
            model_name='usedmachine',
            name='Image5',
            field=models.ImageField(null=True, upload_to='media/product'),
        ),
    ]
