# Generated by Django 4.1.7 on 2023-09-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0014_usedmachine_image2_usedmachine_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedmachine',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='usedmachine',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='usedmachine',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='usedmachine',
            name='Image5',
        ),
    ]
