# Generated by Django 4.1.7 on 2023-10-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadminpanel', '0015_remove_usedmachine_image2_remove_usedmachine_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('SiderID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/product')),
                ('HeadOne', models.CharField(max_length=255, verbose_name='Heading One')),
                ('HeadTwo', models.CharField(max_length=255, verbose_name='Heading Two')),
                ('LinkOne', models.URLField(max_length=5000)),
                ('LinkTwo', models.URLField(max_length=5000)),
            ],
        ),
    ]
