# Generated by Django 4.2.4 on 2023-08-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_maincategory_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PC', 'Pre-Construction'), ('GC', 'General Contracting'), ('CM', 'Construction Management'), ('DB', 'Design and Build')], max_length=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
