# Generated by Django 4.2.4 on 2023-08-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='mcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.maincategory'),
            preserve_default=False,
        ),
    ]
