# Generated by Django 4.2.4 on 2023-08-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_subcategory_category_subcategory_mcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='mcat',
            new_name='mcategory',
        ),
    ]
