# Generated by Django 4.2.4 on 2023-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_mcat_subcategory_mcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='product'),
        ),
    ]
