# Generated by Django 4.2.4 on 2023-08-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_prodfile_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='mcategory',
            new_name='category',
        ),
    ]
