# Generated by Django 4.2.4 on 2023-08-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_mcategory_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='mcategory',
        ),
    ]
